### ISSUE TITLE
If you launch ProtonMail Desktop App while it is already launched, the following message appears instead of just opening window

### ISSUE THREAD

**Issue by alien2003** [vladimiry/protonmail-desktop-app#18]
Unhandled Promise Rejection
Error: Cannot find module '../tray'
    at Function.Module._resolveFilename (/opt/protonmail-desktop-app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Object.get [as Tray] (/opt/protonmail-desktop-app/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at Object.<anonymous> (/opt/protonmail-desktop-app/resources/app.asar/app/electron/main/index.js:1697:36)
    at Generator.next (<anonymous>)
    at /opt/protonmail-desktop-app/resources/app.asar/app/electron/main/index.js:208:71
    at Promise (<anonymous>)

**Comment by vladimiry** [comment]
What is the app used version and operation system?

If it's not the v0.3.2, can you try it? v0.3.2 has already got some adjustments on regard of this problem, but that might not be enough.

**Comment by alien2003** [comment]
Manjaro Linux. 0.3.1. I'll update to 0.3.2 and try, thx

**Comment by vladimiry** [comment]
@alien2003 have you had any luck with v0.3.2 yet?

**Comment by alien2003** [comment]
@vladimiry 0.3.2 works great for me! Thanks

**Comment by vladimiry** [comment]
This is the applied workaround https://github.com/vladimiry/protonmail-desktop-app/commit/cb3e5d629b5e39d818c081a1b3a2dceb2c6aa847
