### ISSUE TITLE
Failed to run on Ubuntu 16.04 report

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/protonmail-desktop-app#3]
v0.2.0-beta.1

Error: libsodium.so.23: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at load (/opt/protonmail-desktop-app/resources/app.asar/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/opt/protonmail-desktop-app/resources/app.asar/node_modules/sodium-native/index.js:1:194)

**Comment by vladimiry** [comment]
Runs well on Arch Linux. Need to investigate the case.

**Comment by vladimiry** [comment]
Applied workaround of unpacking `sodium-native` module from the asar archive https://github.com/vladimiry/protonmail-desktop-app/commit/b6485a22bc4d1be657b71019f4e40ad2908902cc#diff-16c2a798a0e2b6675d5675ff89ece034R42 makes it work on Ubuntu 16.04
