### ISSUE TITLE
Failed to start in Linux Mint 18.2 (Cinnamon, 64-bit)

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/protonmail-desktop-app#9]
[Provided error log](https://www.reddit.com/r/ProtonMail/comments/7ve8vi/unofficial_protonmail_desktop_app/dtrlkoi/):
`
Unhandled Promise Rejection Error: Cannot find module '../tray' at Function.Module._resolveFilename (/opt/protonmail-desktop-app/resources/electron.asar/common/reset-search-paths.js:35:12) at Object.get as Tray at Object.<anonymous> (/opt/protonmail-desktop-app/resources/app.asar/app/electron/main/index.js:1665:36) at Generator.next (<anonymous>) at /opt/protonmail-desktop-app/resources/app.asar/app/electron/main/index.js:207:71 at Promise (<anonymous>)
`

**Comment by vladimiry** [comment]
System version:
![mint-version](https://user-images.githubusercontent.com/1560781/35809329-9228c080-0a88-11e8-87de-30c2a97e0a4a.png)

`uname -a` gives this:
```
Linux vy-VirtualBox 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Steps have been executed:
- `wget https://github.com/vladimiry/protonmail-desktop-app/releases/download/v0.2.5/protonmail-desktop-app-0.2.5-linux-amd64.deb`
- `dpkg -i protonmail-desktop-app-0.2.5-linux-amd64.deb`
- `/opt/protonmail-desktop-app/protonmail-desktop-app`

Program successfully started:
![reproduce](https://user-images.githubusercontent.com/1560781/35809769-eac18ae6-0a89-11e8-95ef-a5593da0f41b.png)

So it works on Linux Mint, closing until additional information on error reproducing is provided.
